version: '3.9'

services:
  pihole-control:
    build: .
    container_name: pihole-control-panel
    ports:
      - "2020:5000"  # host:container
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=use-a-unique-random-value-here
    volumes:
      - ./config.py:/app/config.py:ro  # optional: mount config separately
